version: "3.0"

services:
  app:
    build: ./docker
    container_name: "ft_app"
    volumes:
      - ./fasttext:/app
      - ./resources:/app/resources
      - ../log:/tmp/log
    ports:
      - 8887:8887
    tty: true
